version: '3'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    container_name: mongo-db
    ports:
      - '27017:27017'
  node-app:
    image: jsmu/node-app:latest
    environment:
        MONGO_HOST: mongo
        MONGO_PORT: 27017
        MONGO_USERNAME: ${MONGO_USERNAME}
        MONGO_PASSWORD: ${MONGO_PASSWORD}
        MONGO_DATABASE: ${MONGO_DATABASE}
    container_name: node-app
    depends_on:
      - mongo
    ports:
      - "3000:3000"
      