apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-ms
  labels:
    app: mongo-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-ms
  template:
    metadata:
      labels:
        app: mongo-ms
    spec:
      containers:
        - name: mongo-ms
          image: mongo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "unirmongo"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "unirm0ng0"
            - name: MONGO_INITDB_DATABASE
              value: "mongo"