apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-ms
  labels:
    app: mongo-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-ms
  template:
    metadata:
      labels:
        app: mongo-ms
    spec:
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
      containers:
        - name: mongo-ms
          image: mongo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "unirmongo"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "unirm0ng0"
            - name: MONGO_INITDB_DATABASE
              value: "mongo"
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 512Mi