apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: mongo_dsk
    diskURI: /subscriptions/02b9c0e0-8708-46b2-90f1-c26c6f065acc/resourceGroups/rg_aks_exercise/providers/Microsoft.Compute/disks/mongo_dsk