name: Build, Push and Aks Deploy

on:
  push:
    branches:
      - develop

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ secrets.DH_URL }}
        username: ${{ secrets.DH_USERNAME }}
        password: ${{ secrets.DH_PASS }}
        logout: true
    
    - name: Build and push Docker Node Image
      uses: docker/build-push-action@v5.0.0
      with:
        file: ./dockerfile
        push: true
        tags: ${{ secrets.DH_USERNAME}}/node-app:latest
    
    - name: Azure login
      id: login
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Mongo to AKS
      uses: Azure/k8s-deploy@v4
      with:
        namespace: ${{ secrets.AKS_NAMESPACE }}
        manifests: k8s/mongo/*

    - name: Deploy Node to AKS
      uses: Azure/k8s-deploy@v4
      with:
        namespace: ${{ secrets.AKS_NAMESPACE }}
        manifests: k8s/node/*